name: youmao
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dynamic_theme: ^1.0.1
  scoped_model:
  audioplayers: ^0.13.7
  #页面全局变量控制
  redux_thunk: ^0.2.1
  flutter_swiper : ^1.1.4
  cached_network_image: 2.0.0-rc
  flutter_redux: ^0.5.3
  flutter_spinkit: ^3.1.0
  color_thief_flutter: ^1.0.1
  webview_flutter: ^0.3.19+9
  umeng_analytics_plugin: ^1.0.2
  json_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^3.2.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/launch.png
    - assets/more.png
    - assets/datas/hot.json
    - assets/datas/catsound.json
    - assets/datas/banner.json
    - assets/datas/new.json
    - assets/images/cat/1.jpg
    - assets/images/cat/2.jpg
    - assets/images/cat/banner/11.jpg
    - assets/images/cat/banner/13.jpg
    - assets/images/cat/banner/14.jpg
#    猫叫资源，跟首页列表顺序对应
    - assets/images/cat/sound/7.jpg
    - assets/images/cat/sound/9.jpg
    - assets/images/cat/sound/18.jpg
    - assets/images/cat/sound/sleep.jpg
    - assets/images/cat/sound/12.jpg
    - assets/images/cat/sound/5.jpg
    - assets/images/cat/sound/4.jpg
    - assets/images/cat/sound/3.jpg
    - assets/images/cat/sound/6.jpg
#    热门和新的猫图片
    - assets/images/cat/hot/1.jpg
    - assets/images/cat/hot/2.jpg
    - assets/images/cat/hot/3.jpg
    - assets/images/cat/hot/4.jpg
    - assets/images/cat/hot/5.jpg
    - assets/images/cat/hot/6.jpg
    - assets/images/cat/hot/7.jpg
    - assets/images/cat/hot/8.jpg
#    猫叫
    - assets/cat/cat_0.mp3
    - assets/cat/cat_1.mp3
    - assets/cat/cat_3.mp3
    - assets/cat/cat_4.mp3
    - assets/cat/cat_5.mp3
    - assets/cat/cat_6.mp3
    - assets/cat/cat_8.mp3
    - assets/cat/cat_10.mp3
    - assets/cat/cat_28.mp3
    - assets/cat/cat_aggressive.mp3
    - assets/cat/cat_suoni.mp3
    - assets/cat/cat_walk.mp3
    - assets/cat/cat_simonsays.mp3
    - assets/cat/cat_grumpy.mp3
    - assets/cat/cat_gutti.mp3
    - assets/cat/cat_scooter.mp3
    - assets/cat/cat_luna.mp3

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
